[build]
  command = "ls -la && npx ng build --configuration production"  
  publish = "dist/"     

[build.environment]
  NODE_VERSION = "22"                    
  NPM_FLAGS = "--legacy-peer-deps"       

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"


[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"