import type { FuzzyLabelRuleSpec } from "../declarations/fuzzy-label.types";

export const FUZZY_LABEL_DELIMITED_LINE_PATTERN = /^(\s*[^:=\n\r]{2,64}?)\s*[:=]\s*(.+)$/u;

export const FUZZY_LABEL_SPECS: readonly FuzzyLabelRuleSpec[] = Object.freeze([
  {
    aliases: Object.freeze([
      "access token",
      "api key",
      "apikey",
      "client secret",
      "contrasena",
      "contrasenia",
      "passwd",
      "password",
      "passw0rd",
      "passwrod",
      "refresh token",
      "senha",
    ]),
    maxScore: 0.24,
    ruleId: "secret-assignment",
  },
  {
    aliases: Object.freeze([
      "telephone",
      "telefone",
      "telefone principal",
      "telephone principal",
      "teleph0ne",
      "telefon",
      "telefono",
      "telef0no principal",
      "telefono principal",
      "phone number",
      "mobile number",
    ]),
    maxScore: 0.2,
    ruleId: "labeled-phone",
    valuePatternFactory: () => /^\+?[0-9()\s.-]{8,20}\d$/u,
  },
  {
    aliases: Object.freeze([
      "full name",
      "ful name",
      "nomre completo",
      "n0me completo",
      "nome completo",
      "nombre completo",
      "nombre y apellido",
    ]),
    maxScore: 0.22,
    ruleId: "labeled-name",
    valuePatternFactory: () => /^[^\n\r,;]{3,80}$/u,
  },
  {
    aliases: Object.freeze([
      "address",
      "adress",
      "addres5",
      "direccion",
      "direcc1on",
      "d1reccion",
      "direcion",
      "endereco",
      "morada",
    ]),
    maxScore: 0.18,
    ruleId: "labeled-address",
    valuePatternFactory: () => /^[^\n\r]{6,120}$/u,
  },
  {
    aliases: Object.freeze([
      "passport",
      "passport number",
      "passaport",
      "pasport",
      "pasaporte",
      "passaporte",
    ]),
    maxScore: 0.2,
    ruleId: "labeled-passport",
    valuePatternFactory: () => /^[A-Z0-9<]{6,12}$/iu,
  },
  {
    aliases: Object.freeze([
      "carteira nacional de habilitacao",
      "carteira nacional de habi1itacao",
      "carteira nacional habilitacao",
    ]),
    maxScore: 0.2,
    ruleId: "cnh-labeled",
    valuePatternFactory: () => /^\d{11}$/u,
  },
  {
    aliases: Object.freeze([
      "cedula",
      "cedu1a",
      "ceduia",
      "cedula de ciudadania",
      "cedula de identidad",
      "cedula ciudadania",
    ]),
    maxScore: 0.19,
    ruleId: "cedula-labeled",
    valuePatternFactory: () => /^\d{6,12}$/u,
  },
  {
    aliases: Object.freeze([
      "documento nacional de identidad",
      "document national identity",
      "docurnento nacional de identidad",
      "documento nac1onal de identidad",
    ]),
    maxScore: 0.22,
    ruleId: "dni-labeled",
    valuePatternFactory: () => /^\d{7,8}$/u,
  },
  {
    aliases: Object.freeze([
      "registro unico de contribuyentes",
      "registro unico contribuyentes",
      "registro unico de contribullentes",
      "registro un1co de contribuyentes",
    ]),
    maxScore: 0.22,
    ruleId: "ruc-labeled",
    valuePatternFactory: () => /^\d{11,13}$/u,
  },
  {
    aliases: Object.freeze([
      "numero de identificacao fiscal",
      "numero identificacao fiscal",
      "nurnero de identificacao fiscal",
      "numero de identificacao fisca1",
      "numero de identifcacao fiscal",
    ]),
    maxScore: 0.27,
    ruleId: "pt-nif-labeled",
    valuePatternFactory: () => /^\d{9}$/u,
  },
  {
    aliases: Object.freeze([
      "numero de identificacao da seguranca social",
      "numero identificacao seguranca social",
      "nurnero de identificacao da seguranca social",
      "numero de identifcacao da seguranca social",
      "numero de identificacao da seguranca soclal",
      "numero de identificacao da seguranca soc1al",
    ]),
    maxScore: 0.22,
    ruleId: "pt-niss-labeled",
    valuePatternFactory: () => /^\d{11}$/u,
  },
  {
    aliases: Object.freeze([
      "documento nacional de identidad",
      "docurnento nacional de identidad",
      "documento nac1onal de identidad",
      "documento nacional de ident1dad",
    ]),
    maxScore: 0.2,
    ruleId: "es-dni-labeled",
    valuePatternFactory: () => /^\d{8}[A-Z]$/iu,
  },
  {
    aliases: Object.freeze([
      "numero de identidad de extranjero",
      "numero identidad extranjero",
      "nurnero de identidad de extranjero",
      "numero de identidad de extrangero",
      "numero de identidad de estranjero",
      "numero de ident1dad de extranjero",
    ]),
    maxScore: 0.2,
    ruleId: "es-nie-labeled",
    valuePatternFactory: () => /^[XYZ]\d{7}[A-Z]$/iu,
  },
  {
    aliases: Object.freeze([
      "national id",
      "resident id",
      "shenfenzheng",
      "shen fen zheng",
      "shenfen zheng",
      "shen fenzheng",
      "shenfenzheng hao",
    ]),
    maxScore: 0.2,
    ruleId: "cn-resident-id-labeled",
    valuePatternFactory: () => /^\d{17}[\dXx]$/u,
  },
  {
    aliases: Object.freeze([
      "snils",
      "sni1s",
      "snil5",
      "snlis",
      "snils number",
    ]),
    maxScore: 0.18,
    ruleId: "ru-snils-labeled",
    valuePatternFactory: () => /^\d{3}-?\d{3}-?\d{3}\s?\d{2}$/u,
  },
  {
    aliases: Object.freeze([
      "aadhaar",
      "aadhar",
      "aadhr",
      "aaadhaar",
      "adhaar",
      "aadhaar card",
      "aadhar card number",
    ]),
    maxScore: 0.21,
    ruleId: "in-aadhaar-labeled",
    valuePatternFactory: () => /^\d{4}\s?\d{4}\s?\d{4}$/u,
  },
  {
    aliases: Object.freeze([
      "permanent account number",
      "permament account number",
      "permanent acount number",
      "permanent account nurnber",
      "permanent acct number",
    ]),
    maxScore: 0.22,
    ruleId: "in-pan-labeled",
    valuePatternFactory: () => /^[A-Z]{5}\d{4}[A-Z]$/iu,
  },
  {
    aliases: Object.freeze([
      "goods and services tax number",
      "goods and services tax nurnber",
      "goods services tax number",
      "goods & services tax number",
      "gst nurnber",
    ]),
    maxScore: 0.24,
    ruleId: "in-gstin-labeled",
    valuePatternFactory: () => /^\d{2}[A-Z]{5}\d{4}[A-Z][A-Z0-9][Zz][A-Z0-9]$/iu,
  },
]);
