import type { DetectionRule } from "../declarations/masking.types";
import {
  isLikelyBrazilianStateId,
  isLikelyCreditCard,
  isLikelyIban,
  isLikelyPhoneNumber,
  isValidChileanRut,
  isValidCnpj,
  isValidCpf,
  isValidPisPasep,
  looksLikeBrazilianVoterId,
  looksLikeLatamNationalId,
  looksLikeLatamTaxId,
  looksLikeStructuredAddress,
  looksLikeStructuredName,
  looksSecretLike,
} from "../utils/mask-validation.utils";

export const MASKING_RULES: readonly DetectionRule[] = Object.freeze([
  {
    category: "personal",
    coverage: "global",
    confidence: "high",
    id: "email-address",
    label: "Email address",
    locale: "shared",
    patternFactory: () => /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/giu,
    priority: 120,
  },
  {
    category: "credential",
    coverage: "global",
    confidence: "high",
    id: "jwt-token",
    label: "JWT token",
    locale: "shared",
    patternFactory: () => /\beyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\b/gu,
    priority: 130,
  },
  {
    category: "credential",
    coverage: "global",
    confidence: "high",
    id: "openai-style-key",
    label: "API key",
    locale: "shared",
    patternFactory: () => /\bsk-(?:proj-|live-|test-)?[A-Za-z0-9_-]{20,}\b/gu,
    priority: 130,
  },
  {
    category: "credential",
    coverage: "global",
    confidence: "high",
    id: "aws-access-key",
    label: "AWS access key",
    locale: "shared",
    patternFactory: () => /\b(?:AKIA|ASIA)[A-Z0-9]{16}\b/g,
    priority: 125,
  },
  {
    category: "credential",
    coverage: "global",
    confidence: "high",
    id: "aws-secret-key",
    label: "AWS secret access key",
    locale: "shared",
    patternFactory: () =>
      /\baws[_-]?secret[_-]?access[_-]?key\b\s*[:=]\s*["']?([A-Za-z0-9/+=]{40})["']?/giu,
    priority: 126,
    valueGroup: 1,
  },
  {
    category: "credential",
    coverage: "global",
    confidence: "high",
    id: "github-pat",
    label: "GitHub token",
    locale: "shared",
    patternFactory: () => /\bgh[pousr]_[A-Za-z0-9]{20,}\b/gu,
    priority: 126,
  },
  {
    category: "credential",
    coverage: "global",
    confidence: "high",
    id: "slack-webhook",
    label: "Slack webhook",
    locale: "shared",
    patternFactory: () =>
      /https:\/\/hooks\.slack\.com\/services\/T[A-Z0-9]{8,}\/B[A-Z0-9]{8,}\/[A-Za-z0-9]{20,}/gu,
    priority: 126,
  },
  {
    category: "credential",
    coverage: "global",
    confidence: "high",
    id: "secret-assignment",
    label: "Credential assignment",
    locale: "shared",
    patternFactory: () =>
      /\b(?:access[_-]?token|api[_-]?key|client[_-]?secret|password|refresh[_-]?token|secret|senha|token|contrase(?:n|ñ)a)\b\s*[:=]\s*["']?([A-Za-z0-9._~+/=-]{8,})["']?/giu,
    priority: 118,
    validator: looksSecretLike,
    valueGroup: 1,
  },
  {
    category: "credential",
    coverage: "global",
    confidence: "high",
    id: "bearer-token",
    label: "Bearer token",
    locale: "shared",
    patternFactory: () => /\bBearer\s+([A-Za-z0-9\-._~+/]+=*)/gu,
    priority: 117,
    validator: looksSecretLike,
    valueGroup: 1,
  },
  {
    category: "financial",
    coverage: "global",
    confidence: "high",
    id: "credit-card",
    label: "Credit card number",
    locale: "shared",
    patternFactory: () => /\b(?:\d[ -]?){13,19}\b/g,
    priority: 114,
    validator: isLikelyCreditCard,
  },
  {
    category: "financial",
    coverage: "global",
    confidence: "high",
    id: "iban",
    label: "IBAN",
    locale: "shared",
    patternFactory: () => /\b[A-Z]{2}\d{2}[A-Z0-9]{11,30}\b/gu,
    priority: 108,
    validator: isLikelyIban,
  },
  {
    category: "identifier",
    countryProfileIds: ["us"],
    coverage: "country",
    confidence: "high",
    id: "us-ssn",
    label: "US Social Security number",
    locale: "en-US",
    patternFactory: () => /\b\d{3}-\d{2}-\d{4}\b/g,
    priority: 116,
  },
  {
    category: "personal",
    countryProfileIds: ["us"],
    coverage: "country",
    confidence: "medium",
    id: "us-phone",
    label: "US phone number",
    locale: "en-US",
    patternFactory: () =>
      /(?:\+1[\s.-]?)?(?:\([2-9]\d{2}\)|[2-9]\d{2})[\s.-]?\d{3}[\s.-]?\d{4}\b/g,
    priority: 86,
    validator: isLikelyPhoneNumber,
  },
  {
    category: "identifier",
    countryProfileIds: ["br"],
    coverage: "country",
    confidence: "high",
    id: "cpf",
    label: "CPF",
    locale: "pt-BR",
    patternFactory: () => /\b\d{3}\.?\d{3}\.?\d{3}-?\d{2}\b/g,
    priority: 122,
    validator: isValidCpf,
  },
  {
    category: "identifier",
    countryProfileIds: ["br"],
    coverage: "country",
    confidence: "high",
    id: "cnpj",
    label: "CNPJ",
    locale: "pt-BR",
    patternFactory: () => /\b\d{2}\.?\d{3}\.?\d{3}\/?\d{4}-?\d{2}\b/g,
    priority: 122,
    validator: isValidCnpj,
  },
  {
    category: "personal",
    countryProfileIds: ["br"],
    coverage: "country",
    confidence: "medium",
    id: "br-phone",
    label: "Brazil phone number",
    locale: "pt-BR",
    patternFactory: () => /(?:\+55\s?)?(?:\(?\d{2}\)?\s?)?9?\d{4}-?\d{4}\b/g,
    priority: 84,
    validator: isLikelyPhoneNumber,
  },
  {
    category: "location",
    countryProfileIds: ["br"],
    coverage: "country",
    confidence: "high",
    id: "cep-labeled",
    label: "CEP",
    locale: "pt-BR",
    patternFactory: () => /\b(?:cep)\b\s*[:=-]\s*(\d{5}-?\d{3})\b/giu,
    priority: 109,
    valueGroup: 1,
  },
  {
    category: "identifier",
    countryProfileIds: ["br"],
    coverage: "country",
    confidence: "high",
    id: "cnh-labeled",
    label: "CNH",
    locale: "pt-BR",
    patternFactory: () =>
      /\b(?:cnh|carteira\s*nacional\s*de\s*habilita(?:c|ç)[aã]o)\b\s*[:=-]\s*(\d{11})/giu,
    priority: 110,
    valueGroup: 1,
  },
  {
    category: "identifier",
    countryProfileIds: ["br"],
    coverage: "country",
    confidence: "high",
    id: "pis-pasep-labeled",
    label: "PIS/PASEP",
    locale: "pt-BR",
    patternFactory: () =>
      /\b(?:nis|pis|pasep)\b\s*[:=-]\s*(\d{3}\.?\d{5}\.?\d{2}-?\d|\d{11})\b/giu,
    priority: 111,
    validator: isValidPisPasep,
    valueGroup: 1,
  },
  {
    category: "identifier",
    countryProfileIds: ["br"],
    coverage: "country",
    confidence: "high",
    id: "rg-labeled",
    label: "RG",
    locale: "pt-BR",
    patternFactory: () =>
      /\b(?:rg|registro\s+geral|identidade)\b\s*[:=-]\s*([0-9]{1,2}\.?\d{3}\.?\d{3}-?[\dXx])\b/giu,
    priority: 111,
    validator: isLikelyBrazilianStateId,
    valueGroup: 1,
  },
  {
    category: "identifier",
    countryProfileIds: ["br"],
    coverage: "country",
    confidence: "medium",
    id: "titulo-eleitor-labeled",
    label: "Titulo de eleitor",
    locale: "pt-BR",
    patternFactory: () =>
      /\b(?:t[ií]tulo(?:\s+de)?\s+eleitor)\b\s*[:=-]\s*((?:\d[\s.-]*){12})/giu,
    priority: 100,
    validator: looksLikeBrazilianVoterId,
    valueGroup: 1,
  },
  {
    category: "identifier",
    countryProfileIds: ["cl"],
    coverage: "country",
    confidence: "high",
    id: "chile-rut",
    label: "Chilean RUT",
    locale: "es-LatAm",
    patternFactory: () => /\b\d{1,2}\.?\d{3}\.?\d{3}-?[\dKk]\b/gu,
    priority: 121,
    validator: isValidChileanRut,
  },
  {
    category: "identifier",
    countryProfileIds: ["mx"],
    coverage: "country",
    confidence: "high",
    id: "curp",
    label: "CURP",
    locale: "es-LatAm",
    patternFactory: () => /\b[A-Z]{4}\d{6}[HM][A-Z]{5}[A-Z0-9]\d\b/g,
    priority: 120,
  },
  {
    category: "identifier",
    countryProfileIds: ["mx"],
    coverage: "country",
    confidence: "high",
    id: "rfc",
    label: "RFC",
    locale: "es-LatAm",
    patternFactory: () => /\b[A-Z&Ñ]{3,4}\d{6}[A-Z0-9]{3}\b/giu,
    priority: 114,
  },
  {
    category: "identifier",
    countryProfileIds: ["ar"],
    coverage: "country",
    confidence: "high",
    id: "cuit",
    label: "CUIT",
    locale: "es-LatAm",
    patternFactory: () => /\b\d{2}-\d{8}-\d\b/g,
    priority: 116,
  },
  {
    category: "identifier",
    countryProfileIds: ["co"],
    coverage: "country",
    confidence: "high",
    id: "nit",
    label: "NIT",
    locale: "es-LatAm",
    patternFactory: () => /\b\d{3}\.?\d{3}\.?\d{3}-?\d\b/g,
    priority: 112,
  },
  {
    category: "identifier",
    countryProfileIds: ["co"],
    coverage: "country",
    confidence: "high",
    id: "cedula-labeled",
    label: "Cedula",
    locale: "es-LatAm",
    patternFactory: () =>
      /\b(?:c[eé]dula(?:\s+de\s+(?:ciudadan[ií]a|identidad))?)\b\s*[:=-]\s*(\d{6,12})\b/giu,
    priority: 115,
    validator: looksLikeLatamNationalId,
    valueGroup: 1,
  },
  {
    category: "identifier",
    countryProfileIds: ["ar", "pe"],
    coverage: "country",
    confidence: "high",
    id: "dni-labeled",
    label: "DNI",
    locale: "es-LatAm",
    patternFactory: () =>
      /\b(?:dni|documento\s+nacional\s+de\s+identidad)\b\s*[:=-]\s*(\d{7,8})\b/giu,
    priority: 110,
    validator: looksLikeLatamNationalId,
    valueGroup: 1,
  },
  {
    category: "identifier",
    countryProfileIds: ["pe"],
    coverage: "country",
    confidence: "high",
    id: "ruc-labeled",
    label: "RUC",
    locale: "es-LatAm",
    patternFactory: () => /\b(?:ruc)\b\s*[:=-]\s*(\d{11,13})\b/giu,
    priority: 110,
    validator: looksLikeLatamTaxId,
    valueGroup: 1,
  },
  {
    category: "personal",
    coverage: "global",
    confidence: "medium",
    id: "labeled-phone",
    label: "Labeled phone number",
    locale: "shared",
    patternFactory: () =>
      /\b(?:celular|m[oó]vil|movil|phone|tel(?:é|e)?fono|telefone)\b\s*[:=-]\s*(\+?[0-9()\s.-]{8,20}\d)/giu,
    priority: 96,
    validator: isLikelyPhoneNumber,
    valueGroup: 1,
  },
  {
    category: "personal",
    coverage: "global",
    confidence: "medium",
    id: "labeled-name",
    label: "Labeled full name",
    locale: "shared",
    patternFactory: () =>
      /\b(?:full\s*name|name|nome(?:\s+completo)?|nombre(?:\s+completo)?)\b\s*[:=-]\s*([^\n\r,;]{3,80})/giu,
    priority: 44,
    validator: looksLikeStructuredName,
    valueGroup: 1,
  },
  {
    category: "location",
    coverage: "global",
    confidence: "medium",
    id: "labeled-address",
    label: "Labeled address",
    locale: "shared",
    patternFactory: () =>
      /\b(?:address|direcci[oó]n|endere(?:c|ç)o)\b\s*[:=-]\s*([^\n\r]{6,120})/giu,
    priority: 42,
    validator: looksLikeStructuredAddress,
    valueGroup: 1,
  },
  {
    category: "identifier",
    coverage: "global",
    confidence: "medium",
    id: "labeled-passport",
    label: "Passport number",
    locale: "shared",
    patternFactory: () =>
      /\b(?:passport|pasaporte|passaporte)\b(?:\s*(?:no|number|n[uú]mero))?\s*[:=-]\s*([A-Z0-9<]{6,12})/giu,
    priority: 92,
    valueGroup: 1,
  },
]);
