apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: llm-prompt-purify
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  ConnectionStrings__FeedbackDatabase: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@mongo:27017/llm_prompt_purify?authSource=admin"
  DeveloperEmail__EnableSsl: "true"
  DeveloperEmail__RecipientEmail: "aronprogramador@gmail.com"
  AllowedOrigins__0: "https://llm-prompt-purify.example.com"
  AllowedOrigins__1: "http://localhost:4200"
