/** Ported from Angular app — platform-agnostic constants. */
import type { DetectionRule } from "../declarations/masking.types";
import {
  BR_CEP_LABEL_FLAGS,
  BR_CNH_LABEL_FLAGS,
  BR_PIS_PASEP_LABEL_FLAGS,
  BR_RG_LABEL_FLAGS,
  BR_VOTER_LABEL_FLAGS,
  CN_RESIDENT_ID_LABEL_FLAGS,
  ES_DNI_LABEL_FLAGS,
  ES_NIE_LABEL_FLAGS,
  IN_AADHAAR_LABEL_FLAGS,
  IN_GSTIN_LABEL_FLAGS,
  IN_PAN_LABEL_FLAGS,
  LATAM_CEDULA_LABEL_FLAGS,
  LATAM_DNI_LABEL_FLAGS,
  LATAM_RUC_LABEL_FLAGS,
  PT_NIF_LABEL_FLAGS,
  PT_NISS_LABEL_FLAGS,
  RU_INN_LABEL_FLAGS,
  RU_SNILS_LABEL_FLAGS,
  SECRET_ASSIGNMENT_FLAGS,
  SHARED_ADDRESS_LABEL_FLAGS,
  SHARED_NAME_LABEL_FLAGS,
  SHARED_PASSPORT_LABEL_FLAGS,
  SHARED_PHONE_LABEL_FLAGS,
} from "./mask-flag-dictionaries.constants";
import {
  isValidArgentineCuit,
  isLikelyBrazilianStateId,
  isValidChineseResidentId,
  isValidColombianNit,
  isLikelyCreditCard,
  isLikelyIban,
  isLikelyPhoneNumber,
  isValidChileanRut,
  isValidCnpj,
  isValidCpf,
  isValidIndianAadhaar,
  isValidPeruvianRuc,
  isValidPisPasep,
  isValidPortugueseNif,
  isValidRussianInn,
  isValidRussianSnils,
  isValidSpanishDni,
  isValidSpanishNie,
  looksLikeBrazilianVoterId,
  looksLikeLatamNationalId,
  looksLikeLatamTaxId,
  looksLikeStructuredAddress,
  looksLikeStructuredName,
  looksSecretLike,
} from "../utils/mask-validation.utils";
import { createDelimitedLabelValuePattern } from "../utils/mask-pattern.utils";

export const MASKING_RULES: readonly DetectionRule[] = Object.freeze([
  {
    category: "personal",
    coverage: "global",
    confidence: "high",
    id: "email-address",
    label: "Email address",
    locale: "shared",
    patternFactory: () => /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/giu,
    priority: 120,
  },
  {
    category: "credential",
    coverage: "global",
    confidence: "high",
    id: "jwt-token",
    label: "JWT token",
    locale: "shared",
    patternFactory: () =>
      /\beyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\b/gu,
    priority: 130,
  },
  {
    category: "credential",
    coverage: "global",
    confidence: "high",
    id: "openai-style-key",
    label: "API key",
    locale: "shared",
    patternFactory: () => /\bsk-(?:proj-|live-|test-)?[A-Za-z0-9_-]{20,}\b/gu,
    priority: 130,
  },
  {
    category: "credential",
    coverage: "global",
    confidence: "high",
    id: "aws-access-key",
    label: "AWS access key",
    locale: "shared",
    patternFactory: () => /\b(?:AKIA|ASIA)[A-Z0-9]{16}\b/g,
    priority: 125,
  },
  {
    category: "credential",
    coverage: "global",
    confidence: "high",
    id: "aws-secret-key",
    label: "AWS secret access key",
    locale: "shared",
    patternFactory: () =>
      /\baws[_-]?secret[_-]?access[_-]?key\b\s*[:=]\s*["']?([A-Za-z0-9/+=]{40})["']?/giu,
    priority: 126,
    valueGroup: 1,
  },
  {
    category: "credential",
    coverage: "global",
    confidence: "high",
    id: "github-pat",
    label: "GitHub token",
    locale: "shared",
    patternFactory: () => /\bgh[pousr]_[A-Za-z0-9]{20,}\b/gu,
    priority: 126,
  },
  {
    category: "credential",
    coverage: "global",
    confidence: "high",
    id: "slack-webhook",
    label: "Slack webhook",
    locale: "shared",
    patternFactory: () =>
      /https:\/\/hooks\.slack\.com\/services\/T[A-Z0-9]{8,}\/B[A-Z0-9]{8,}\/[A-Za-z0-9]{20,}/gu,
    priority: 126,
  },
  {
    category: "credential",
    coverage: "global",
    confidence: "high",
    id: "secret-assignment",
    label: "Credential assignment",
    locale: "shared",
    patternFactory: () =>
      createDelimitedLabelValuePattern(
        SECRET_ASSIGNMENT_FLAGS,
        String.raw`[A-Za-z0-9._~+/=-]{8,}`,
        { delimiterPattern: String.raw`[:=]`, quoteWrapped: true },
      ),
    priority: 118,
    validator: looksSecretLike,
    valueGroup: 1,
  },
  {
    category: "credential",
    coverage: "global",
    confidence: "high",
    id: "bearer-token",
    label: "Bearer token",
    locale: "shared",
    patternFactory: () => /\bBearer\s+([A-Za-z0-9\-._~+/]+=*)/gu,
    priority: 117,
    validator: looksSecretLike,
    valueGroup: 1,
  },
  {
    category: "financial",
    coverage: "global",
    confidence: "high",
    id: "credit-card",
    label: "Credit card number",
    locale: "shared",
    patternFactory: () => /\b(?:\d[ -]?){13,19}\b/g,
    priority: 114,
    validator: isLikelyCreditCard,
  },
  {
    category: "financial",
    coverage: "global",
    confidence: "high",
    id: "iban",
    label: "IBAN",
    locale: "shared",
    patternFactory: () => /\b[A-Z]{2}\d{2}[A-Z0-9]{11,30}\b/gu,
    priority: 108,
    validator: isLikelyIban,
  },
  {
    category: "identifier",
    countryProfileIds: ["us"],
    coverage: "country",
    confidence: "high",
    id: "us-ssn",
    label: "US Social Security number",
    locale: "en-US",
    patternFactory: () => /\b\d{3}-\d{2}-\d{4}\b/g,
    priority: 116,
  },
  {
    category: "personal",
    countryProfileIds: ["us"],
    coverage: "country",
    confidence: "medium",
    id: "us-phone",
    label: "US phone number",
    locale: "en-US",
    patternFactory: () =>
      /(?:\+1[\s.-]?)?(?:\([2-9]\d{2}\)|[2-9]\d{2})[\s.-]?\d{3}[\s.-]?\d{4}\b/g,
    priority: 86,
    validator: isLikelyPhoneNumber,
  },
  {
    category: "identifier",
    countryProfileIds: ["br"],
    coverage: "country",
    confidence: "high",
    id: "cpf",
    label: "CPF",
    locale: "pt-BR",
    patternFactory: () => /\b\d{3}\.?\d{3}\.?\d{3}-?\d{2}\b/g,
    priority: 122,
    validator: isValidCpf,
  },
  {
    category: "identifier",
    countryProfileIds: ["br"],
    coverage: "country",
    confidence: "high",
    id: "cnpj",
    label: "CNPJ",
    locale: "pt-BR",
    patternFactory: () => /\b\d{2}\.?\d{3}\.?\d{3}\/?\d{4}-?\d{2}\b/g,
    priority: 122,
    validator: isValidCnpj,
  },
  {
    category: "personal",
    countryProfileIds: ["br"],
    coverage: "country",
    confidence: "medium",
    id: "br-phone",
    label: "Brazil phone number",
    locale: "pt-BR",
    patternFactory: () => /(?:\+55\s?)?(?:\(?\d{2}\)?\s?)?9?\d{4}-?\d{4}\b/g,
    priority: 84,
    validator: isLikelyPhoneNumber,
  },
  {
    category: "location",
    countryProfileIds: ["br"],
    coverage: "country",
    confidence: "high",
    id: "cep-labeled",
    label: "CEP",
    locale: "pt-BR",
    patternFactory: () =>
      createDelimitedLabelValuePattern(
        BR_CEP_LABEL_FLAGS,
        String.raw`\d{5}-?\d{3}`,
      ),
    priority: 109,
    valueGroup: 1,
  },
  {
    category: "identifier",
    countryProfileIds: ["br"],
    coverage: "country",
    confidence: "high",
    id: "cnh-labeled",
    label: "CNH",
    locale: "pt-BR",
    patternFactory: () =>
      createDelimitedLabelValuePattern(BR_CNH_LABEL_FLAGS, String.raw`\d{11}`),
    priority: 110,
    valueGroup: 1,
  },
  {
    category: "identifier",
    countryProfileIds: ["br"],
    coverage: "country",
    confidence: "high",
    id: "pis-pasep-labeled",
    label: "PIS/PASEP",
    locale: "pt-BR",
    patternFactory: () =>
      createDelimitedLabelValuePattern(
        BR_PIS_PASEP_LABEL_FLAGS,
        String.raw`\d{3}\.?\d{5}\.?\d{2}-?\d|\d{11}`,
      ),
    priority: 111,
    validator: isValidPisPasep,
    valueGroup: 1,
  },
  {
    category: "identifier",
    countryProfileIds: ["br"],
    coverage: "country",
    confidence: "high",
    id: "rg-labeled",
    label: "RG",
    locale: "pt-BR",
    patternFactory: () =>
      createDelimitedLabelValuePattern(
        BR_RG_LABEL_FLAGS,
        String.raw`[0-9]{1,2}\.?\d{3}\.?\d{3}-?[\dXx]`,
      ),
    priority: 111,
    validator: isLikelyBrazilianStateId,
    valueGroup: 1,
  },
  {
    category: "identifier",
    countryProfileIds: ["br"],
    coverage: "country",
    confidence: "medium",
    id: "titulo-eleitor-labeled",
    label: "Titulo de eleitor",
    locale: "pt-BR",
    patternFactory: () =>
      createDelimitedLabelValuePattern(
        BR_VOTER_LABEL_FLAGS,
        String.raw`(?:\d[\s.-]*){12}`,
      ),
    priority: 100,
    validator: looksLikeBrazilianVoterId,
    valueGroup: 1,
  },
  {
    category: "identifier",
    countryProfileIds: ["cl", "latam-es"],
    coverage: "country",
    confidence: "high",
    id: "chile-rut",
    label: "Chilean RUT",
    locale: "es-LatAm",
    patternFactory: () => /\b\d{1,2}\.?\d{3}\.?\d{3}-?[\dKk]\b/gu,
    priority: 121,
    validator: isValidChileanRut,
  },
  {
    category: "identifier",
    countryProfileIds: ["mx", "latam-es"],
    coverage: "country",
    confidence: "high",
    id: "curp",
    label: "CURP",
    locale: "es-LatAm",
    patternFactory: () => /\b[A-Z]{4}\d{6}[HM][A-Z]{5}[A-Z0-9]\d\b/g,
    priority: 120,
  },
  {
    category: "identifier",
    countryProfileIds: ["mx", "latam-es"],
    coverage: "country",
    confidence: "high",
    id: "rfc",
    label: "RFC",
    locale: "es-LatAm",
    patternFactory: () => /\b[A-Z&Ñ]{3,4}\d{6}[A-Z0-9]{3}\b/giu,
    priority: 114,
  },
  {
    category: "identifier",
    countryProfileIds: ["ar", "latam-es"],
    coverage: "country",
    confidence: "high",
    id: "cuit",
    label: "CUIT",
    locale: "es-LatAm",
    patternFactory: () => /\b\d{2}-\d{8}-\d\b/g,
    priority: 116,
    validator: isValidArgentineCuit,
  },
  {
    category: "identifier",
    countryProfileIds: ["co", "latam-es"],
    coverage: "country",
    confidence: "high",
    id: "nit",
    label: "NIT",
    locale: "es-LatAm",
    patternFactory: () => /\b\d{3}\.?\d{3}\.?\d{3}-?\d\b/g,
    priority: 112,
    validator: isValidColombianNit,
  },
  {
    category: "identifier",
    countryProfileIds: ["co", "latam-es"],
    coverage: "country",
    confidence: "high",
    id: "cedula-labeled",
    label: "Cedula",
    locale: "es-LatAm",
    patternFactory: () =>
      createDelimitedLabelValuePattern(
        LATAM_CEDULA_LABEL_FLAGS,
        String.raw`\d{6,12}`,
      ),
    priority: 115,
    validator: looksLikeLatamNationalId,
    valueGroup: 1,
  },
  {
    category: "identifier",
    countryProfileIds: ["ar", "latam-es", "pe"],
    coverage: "country",
    confidence: "high",
    id: "dni-labeled",
    label: "DNI",
    locale: "es-LatAm",
    patternFactory: () =>
      createDelimitedLabelValuePattern(
        LATAM_DNI_LABEL_FLAGS,
        String.raw`\d{7,8}`,
      ),
    priority: 110,
    validator: looksLikeLatamNationalId,
    valueGroup: 1,
  },
  {
    category: "identifier",
    countryProfileIds: ["latam-es", "pe"],
    coverage: "country",
    confidence: "high",
    id: "ruc-labeled",
    label: "RUC",
    locale: "es-LatAm",
    patternFactory: () =>
      createDelimitedLabelValuePattern(
        LATAM_RUC_LABEL_FLAGS,
        String.raw`\d{11,13}`,
      ),
    priority: 110,
    validator: isValidPeruvianRuc,
    valueGroup: 1,
  },
  {
    category: "identifier",
    countryProfileIds: ["pt"],
    coverage: "country",
    confidence: "high",
    id: "pt-nif-labeled",
    label: "NIF",
    locale: "pt-PT",
    patternFactory: () =>
      createDelimitedLabelValuePattern(PT_NIF_LABEL_FLAGS, String.raw`\d{9}`),
    priority: 112,
    validator: isValidPortugueseNif,
    valueGroup: 1,
  },
  {
    category: "identifier",
    countryProfileIds: ["pt"],
    coverage: "country",
    confidence: "medium",
    id: "pt-niss-labeled",
    label: "NISS",
    locale: "pt-PT",
    patternFactory: () =>
      createDelimitedLabelValuePattern(PT_NISS_LABEL_FLAGS, String.raw`\d{11}`),
    priority: 102,
    validator: looksLikeLatamTaxId,
    valueGroup: 1,
  },
  {
    category: "identifier",
    countryProfileIds: ["es"],
    coverage: "country",
    confidence: "high",
    id: "es-dni-labeled",
    label: "Spanish DNI",
    locale: "es-ES",
    patternFactory: () =>
      createDelimitedLabelValuePattern(
        ES_DNI_LABEL_FLAGS,
        String.raw`\d{8}[A-Z]`,
      ),
    priority: 114,
    validator: isValidSpanishDni,
    valueGroup: 1,
  },
  {
    category: "identifier",
    countryProfileIds: ["es"],
    coverage: "country",
    confidence: "high",
    id: "es-nie-labeled",
    label: "Spanish NIE",
    locale: "es-ES",
    patternFactory: () =>
      createDelimitedLabelValuePattern(
        ES_NIE_LABEL_FLAGS,
        String.raw`[XYZ]\d{7}[A-Z]`,
      ),
    priority: 113,
    validator: isValidSpanishNie,
    valueGroup: 1,
  },
  {
    category: "identifier",
    countryProfileIds: ["cn"],
    coverage: "country",
    confidence: "high",
    id: "cn-resident-id-labeled",
    label: "Chinese resident ID",
    locale: "zh-CN",
    patternFactory: () =>
      createDelimitedLabelValuePattern(
        CN_RESIDENT_ID_LABEL_FLAGS,
        String.raw`\d{17}[\dXx]`,
      ),
    priority: 113,
    validator: isValidChineseResidentId,
    valueGroup: 1,
  },
  {
    category: "personal",
    countryProfileIds: ["cn"],
    coverage: "country",
    confidence: "medium",
    id: "cn-phone",
    label: "China phone number",
    locale: "zh-CN",
    patternFactory: () => /(?:\+?86[\s-]?)?1[3-9]\d[\s-]?\d{4}[\s-]?\d{4}\b/g,
    priority: 99,
    validator: isLikelyPhoneNumber,
  },
  {
    category: "identifier",
    countryProfileIds: ["ru"],
    coverage: "country",
    confidence: "high",
    id: "ru-inn-labeled",
    label: "Russian INN",
    locale: "ru-RU",
    patternFactory: () =>
      createDelimitedLabelValuePattern(
        RU_INN_LABEL_FLAGS,
        String.raw`\d{12}|\d{10}`,
      ),
    priority: 112,
    validator: isValidRussianInn,
    valueGroup: 1,
  },
  {
    category: "identifier",
    countryProfileIds: ["ru"],
    coverage: "country",
    confidence: "high",
    id: "ru-snils-labeled",
    label: "Russian SNILS",
    locale: "ru-RU",
    patternFactory: () =>
      createDelimitedLabelValuePattern(
        RU_SNILS_LABEL_FLAGS,
        String.raw`\d{3}-?\d{3}-?\d{3}\s?\d{2}`,
      ),
    priority: 112,
    validator: isValidRussianSnils,
    valueGroup: 1,
  },
  {
    category: "identifier",
    countryProfileIds: ["in"],
    coverage: "country",
    confidence: "high",
    id: "in-aadhaar-labeled",
    label: "Aadhaar",
    locale: "en-IN",
    patternFactory: () =>
      createDelimitedLabelValuePattern(
        IN_AADHAAR_LABEL_FLAGS,
        String.raw`\d{4}\s?\d{4}\s?\d{4}`,
      ),
    priority: 112,
    validator: isValidIndianAadhaar,
    valueGroup: 1,
  },
  {
    category: "identifier",
    countryProfileIds: ["in"],
    coverage: "country",
    confidence: "high",
    id: "in-pan-labeled",
    label: "PAN",
    locale: "en-IN",
    patternFactory: () =>
      createDelimitedLabelValuePattern(
        IN_PAN_LABEL_FLAGS,
        String.raw`[A-Z]{5}\d{4}[A-Z]`,
      ),
    priority: 111,
    valueGroup: 1,
  },
  {
    category: "identifier",
    countryProfileIds: ["in"],
    coverage: "country",
    confidence: "high",
    id: "in-gstin-labeled",
    label: "GSTIN",
    locale: "en-IN",
    patternFactory: () =>
      createDelimitedLabelValuePattern(
        IN_GSTIN_LABEL_FLAGS,
        String.raw`\d{2}[A-Z]{5}\d{4}[A-Z][A-Z0-9][Zz][A-Z0-9]`,
      ),
    priority: 110,
    valueGroup: 1,
  },
  {
    category: "personal",
    coverage: "global",
    confidence: "medium",
    id: "labeled-phone",
    label: "Labeled phone number",
    locale: "shared",
    patternFactory: () =>
      createDelimitedLabelValuePattern(
        SHARED_PHONE_LABEL_FLAGS,
        String.raw`\+?[0-9()\s.-]{8,20}\d`,
      ),
    priority: 96,
    validator: isLikelyPhoneNumber,
    valueGroup: 1,
  },
  {
    category: "personal",
    coverage: "global",
    confidence: "medium",
    id: "labeled-name",
    label: "Labeled full name",
    locale: "shared",
    patternFactory: () =>
      createDelimitedLabelValuePattern(
        SHARED_NAME_LABEL_FLAGS,
        String.raw`[^\n\r,;]{3,80}`,
      ),
    priority: 44,
    validator: looksLikeStructuredName,
    valueGroup: 1,
  },
  {
    category: "location",
    coverage: "global",
    confidence: "medium",
    id: "labeled-address",
    label: "Labeled address",
    locale: "shared",
    patternFactory: () =>
      createDelimitedLabelValuePattern(
        SHARED_ADDRESS_LABEL_FLAGS,
        String.raw`[^\n\r]{6,120}`,
      ),
    priority: 42,
    validator: looksLikeStructuredAddress,
    valueGroup: 1,
  },
  {
    category: "identifier",
    coverage: "global",
    confidence: "medium",
    id: "labeled-passport",
    label: "Passport number",
    locale: "shared",
    patternFactory: () =>
      createDelimitedLabelValuePattern(
        SHARED_PASSPORT_LABEL_FLAGS,
        String.raw`[A-Z0-9<]{6,12}`,
      ),
    priority: 92,
    valueGroup: 1,
  },
]);
