export const appState = {
  compressionLevel: 6,
  regenerateEvent: "pointerup",
  checkAllEvent: "pointerup",
  maskChkCls: "mask-check-field",
  uncheckMaskEvent: "change",
  storageKey: "llmPurifyAppState",
  colorSchemeKey: "colorScheme",
  orderValues: ["asc", "desc"],
  patterns: {
    label: "data-labelpattern",
    sort: "data-sortby",
    order: "data-orderby",
    activeSorting: "data-activesorting",
    fixedTextbox: "data-fixedheight",
    col: "data-col",
    refHead: "data-headref",
  },
  ids: {
    scanTab: "scanResults",
  },
  classes: {
    idxCell: "idx-cell",
    maskCell: "mask-cell",
    labCell: "lab-cell",
    matTb: "mat-mdc-table",
    matTr: "mat-mdc-table-row",
    matTrh: "mat-mdc-header-row",
    matTrAlt: "mat-mdc-table-row-alt",
    matTh: "mat-mdc-header-cell",
    matTd: "mat-mdc-cell",
    matDlgCn: "mat-mdc-dialog-container",
    matDlgCt: "mat-mdc-dialog-content",
    matDlgPn: "mat-mdc-dialog-panel",
    mdDlg: "mdc-dialog",
    matBtn: "mat-button",
    matIcs: "material-icons",
    matIc: "mat-icon",
    matMdIcn: "mat-mdc-icon",
    matIcTp: "mat-icon-no-color",
    matIcBtn: "mat-button__icon",
    matLig: "mat-ligature-font",
  },
};
